apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: portfolio
  annotations:
    cert-manager.io/issuer: letsencrypt-portfolio
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # nginx.ingress.kubernetes.io/ssl-redirect: "true" # Nginx specific
spec:
  # ingressClassName: nginx # Removing to let default controller (Traefik) pick it up
  tls:
    - hosts:
        - lucianojr.com.br
        - lucianojr.pt
      secretName: portfolio-tls
  rules:
    - host: lucianojr.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-service
                port:
                  number: 80
    - host: lucianojr.pt
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-service
                port:
                  number: 80
