apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-portfolio
  namespace: portfolio
spec:
  acme:
    email: luciano@lucianojr.com.br
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-portfolio-key
    solvers:
    - http01:
        ingress: {}
